export { Navbar } from "./Navbar"
export { FigureIntro } from "./FigureIntro"
export { Heropage } from "./Heropage"
export { ComunityRules } from "./ComunityRules"
export { DiscordSection } from "./DiscordSection"
